name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [14]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - run: sudo apt-get install xvfb
    - name: Install and Test
      run: |
        npm ci
        npm run test
        xvfb-run --auto-servernum npm run test:browser
